import Head from 'next/head';
import styles from '../styles/Home.module.css';

import MobileDiv from '../components/MobileDiv';
import Parallax from '../components/Parallax';
import ShowSection from '../components/ShowSection';
import Spotify from '../components/Spotify';
// import { fetchArticles } from '../utils/articles';
import { fetchEvents } from '../utils/events';

export async function getServerSideProps() {
  console.log(JSON.stringify(process.env, null, 2))
  console.error(JSON.stringify(process.env, null, 2))
  const events = await fetchEvents()
  // const articles = await fetchArticles()
  return {
    props: {
      events,
      articles:[]
    }
  }
}

export default function Home({ events, articles, setShowHeaderLogo, showHeaderLogo}) {

  setShowHeaderLogo(false)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Parallax />
      <MobileDiv />
      <Spotify />
      <ShowSection events={events}/>    
    </div>
  )
}
