import Head from "next/head"
import ShopComponent from "../components/ShopComponent"

const Shop = ({setShowHeaderLogo, showHeaderLogo}) => {
  setShowHeaderLogo(true)
  return (
    <div>
      <Head>
        <title>Als Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ShopComponent />
    </div>
  )
}

export default Shop
