import React from "react";
import Head from "next/head"
import ShopComponent from "../components/ShopComponent"
import products from '../products.json';
import { useRouter } from 'next/router'

//...



const Shop = ({ setShowHeaderLogo, showHeaderLogo }) => {
  setShowHeaderLogo(true)
  const router = useRouter()
  
  return (
    <div>
      <Head>
        <title>Als Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.css" />
      </Head>
      <ShopComponent
        products={products}
      />
    </div>
  )
}

export default Shop
